openapi: 3.0.0
info:
  title: Gym Management API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The first name of the user
                lastName:
                  type: string
                  description: The last name of the user
                email:
                  type: string
                  description: The email address of the user
                password:
                  type: string
                  description: The password for the user
                phone:
                  type: string
                  description: The phone number of the user
                personalId:
                  type: string
                  description: The personal ID of the user (e.g., social security number, national ID)
                roles:
                  type: array
                  items:
                    type: string
                  description: The roles the user has (e.g., admin, member)
      responses:
        201:
          description: User registered successfully
        400:
          description: Bad request (e.g., missing or invalid fields)
        500:
          description: Internal server error

  /auth/login:
    post:
      summary: Authenticate and login a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address of the user
                password:
                  type: string
                  description: The password for the user
      responses:
        200:
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token for the authenticated user
        400:
          description: Bad request (e.g., missing or invalid fields)
        401:
          description: Unauthorized (e.g., invalid email or password)
        500:
          description: Internal server error

  /gyms:
    post:
      summary: Create a new gym
      tags:
        - Gyms
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admins:
                  type: array
                  items:
                    type: string
                  description: An array of user IDs representing the gym's admins
                name:
                  type: string
                  description: The name of the gym
                location:
                  type: object
                  properties:
                    latitude:
                      type: number
                      description: The latitude of the gym's location
                    longitude:
                      type: number
                      description: The longitude of the gym's location
                    placeId:
                      type: string
                      description: The Google Maps place ID of the gym's location
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the membership option
                      description:
                        type: string
                        description: A description of the membership option
                      months:
                        type: integer
                        description: The number of months the option covers
                      price:
                        type: number
                        description: The price of the membership option
                      classes:
                        type: array
                        items:
                          type: string
                        description: An array of class IDs included in the membership option
                      weekly:
                        type: integer
                        description: The weekly limit of classes the user can attend with this membership option
                      monthly:
                        type: integer
                        description: The monthly limit of classes the user can attend with this membership option
      responses:
        201:
          description: Gym created successfully
        400:
          description: Bad request (e.g., missing or invalid fields)
        500:
          description: Internal server error
    get:
      summary: Retrieve all gyms
      tags:
        - Gyms
      security:
        - bearerAuth: []
      responses:
        200:
          description: Gyms retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gym'
        500:
          description: Internal server error
  /gyms/{id}:
    get:
      summary: Retrieve a specific gym
      tags:
        - Gyms
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the gym to retrieve
      responses:
        200:
          description: Gym retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gym'
        404:
          description: Gym not found
        500:
          description: Internal server error
    put:
      summary: Update a specific gym
      tags:
        - Gyms
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the gym to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admins:
                  type: array
                  items:
                    type: string
                  description: An array of user IDs representing the gym's admins
                name:
                  type: string
                  description: The name of the gym
                location:
                  type: object
                  properties:
                    latitude:
                      type: number
                      description: The latitude of the gym's location
                    longitude:
                      type: number
                      description: The longitude of the gym's location
                    placeId:
                      type: string
                      description: The Google Maps place ID of the gym's location
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the membership option
                      description:
                        type: string
                        description: A description of the membership option
                      months:
                        type: integer
                        description: The number of months the option covers
                      price:
                        type: number
                        description: The price of the membership option
                      classes:
                        type: array
                        items:
                          type: string
                        description: An array of class IDs included in the membership option
                      weekly:
                        type: integer
                        description: The weekly limit of classes the user can attend with this membership option
                      monthly:
                        type: integer
                        description: The monthly limit of classes the user can attend with this membership option
      responses:
        200:
          description: Gym updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gym'
        404:
          description: Gym not found
        500:
          description: Internal server error
    delete:
      summary: Delete a specific gym
      tags:
        - Gyms
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the gym to delete
      responses:
        200:
          description: Gym deleted successfully
        404:
          description: Gym not found
        500:
          description: Internal server error
  /subscriptions:
    post:
      summary: Create a new subscription
      tags:
        - Subscriptions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user this subscription belongs to
                gymId:
                  type: string
                  description: The ID of the gym this subscription is for
                optionId:
                  type: string
                  description: The ID of the membership option for this subscription
                total:
                  type: number
                  description: The total amount paid for this subscription
                startDate:
                  type: string
                  format: date
                  description: The start date of the subscription
                endDate:
                  type: string
                  format: date
                  description: The end date of the subscription
      responses:
        201:
          description: Subscription created successfully
        400:
          description: Bad request (e.g., missing or invalid fields)
        500:
          description: Internal server error
    get:
      summary: Retrieve all subscriptions
      tags:
        - Subscriptions
      security:
        - bearerAuth: []
      responses:
        200:
          description: Subscriptions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        500:
          description: Internal server error
  /subscriptions/{id}:
    get:
      summary: Retrieve a specific subscription
      tags:
        - Subscriptions
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the subscription to retrieve
      responses:
        200:
          description: Subscription retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        404:
          description: Subscription not found
        500:
          description: Internal server error
    put:
      summary: Update a specific subscription
      tags:
        - Subscriptions
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the subscription to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user this subscription belongs to
                gymId:
                  type: string
                  description: The ID of the gym this subscription is for
                optionId:
                  type: string
                  description: The ID of the membership option for this subscription
                total:
                  type: number
                  description:
                  description: The total amount paid for this subscription
                startDate:
                  type: string
                  format: date
                  description: The start date of the subscription
                endDate:
                  type: string
                  format: date
                  description: The end date of the subscription
      responses:
        200:
          description: Subscription updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        404:
          description: Subscription not found
        500:
          description: Internal server error
    delete:
      summary: Delete a specific subscription
      tags:
        - Subscriptions
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the subscription to delete
      responses:
        200:
          description: Subscription deleted successfully
        404:
          description: Subscription not found
        500:
          description: Internal server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: The user ID
        name:
          type: string
          description: The first name of the user
        lastName:
          type: string
          description: The last name of the user
        email:
          type: string
          description: The email address of the user
        phone:
          type: string
          description: The phone number of the user
        personalId:
          type: string
          description: The personal ID of the user (e.g., social security number, national ID)
        roles:
          type: array
          items:
            type: string
          description: The roles the user has (e.g., admin, member)
    Gym:
      type: object
      properties:
        id:
          type: string
          description: The gym ID
        admins:
          type: array
          items:
            type: string
          description: An array of user IDs representing the gym's admins
        name:
          type: string
          description: The name of the gym
        location:
          type: object
          properties:
            latitude:
              type: number
              description: The latitude of the gym's location
            longitude:
              type: number
              description: The longitude of the gym's location
            placeId:
              type: string
              description: The Google Maps place ID of the gym's location
        options:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the membership option
              description:
                type: string
                description: A description of the membership option
              months:
                type: integer
                description: The number of months the option covers
              price:
                type: number
                description: The price of the membership option
              classes:
                type: array
                items:
                  type: string
                description: An array of class IDs included in the membership option
              weekly:
                type: integer
                description: The weekly limit of classes the user can attend with this membership option
              monthly:
                type: integer
                description: The monthly limit of classes the user can attend with this membership option
    Subscription:
      type: object
      properties:
        id:
          type: string
          description: The subscription ID
        userId:
          type: string
          description: The ID of the user this subscription belongs to
        gymId:
          type:
          type: string
          description: The ID of the gym this subscription is for
        optionId:
          type: string
          description: The ID of the membership option for this subscription
        total:
          type: number
          description: The total amount paid for this subscription
        startDate:
          type: string
          format: date
          description: The start date of the subscription
        endDate:
          type: string
          format: date
          description: The end date of the subscription
    Class:
      type: object
      properties:
        id:
          type: string
          description: The class ID
        name:
          type: string
          description: The name of the class
        instructor:
          type: string
          description: The ID of the instructor for the class
        gymId:
          type: string
          description: The ID of the gym where the class takes place
        startDate:
          type: string
          format: date-time
          description: The start date and time of the class
        endDate:
          type: string
          format: date-time
          description: The end date and time of the class
        capacity:
          type: integer
          description: The maximum number of participants for the class
        attendees:
          type: array
          items:
            type: string
          description: An array of user IDs representing the class attendees

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
